name: toko_bunga
description: "Aplikasi Toko Bunga"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.1
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.7
  intl: ^0.20.1
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:

    #Additional

    - assets/Additional/Profile.png
    - assets/Additional/Flowers.jpg
    - assets/Additional/backgroundSign-In.png
    - assets/Additional/backgroundSign-Up.png
    - assets/Additional/backgroundChat.jpg
    - assets/Additional/backgroundEditProfile.png
    - assets/Additional/backgroundOrderTransaction.png




    #Store
    - assets/Store/Delovery.jpg
    - assets/Store/Florist.jpg
    - assets/Store/Outerbloom.jpg
    - assets/Store/Floranesia.jpg
    - assets/Store/Plantopia.jpg
    - assets/Store/UrbanPlants.jpg
    - assets/Store/GreenSpace.jpg
    - assets/Store/EcoGarden.jpg
    - assets/Store/NatureBloom.jpg
    - assets/Store/FreshGarden.jpg
    - assets/Store/Florania.jpg
    - assets/Store/GreenVista.jpg
    - assets/Store/GreenLeaf.jpg
    - assets/Store/FreshBotanics.jpg


    #Product
    - assets/Product/Flowers/MawarMerah.jpg
    - assets/Product/Flowers/Lavender.jpg
    - assets/Product/Flowers/Camellia.jpg
    - assets/Product/Flowers/Peony.jpg
    - assets/Product/Flowers/Tulip.jpg
    - assets/Product/Flowers/Dahlia.jpg
    - assets/Product/Flowers/Gerbera.jpg
    - assets/Product/Flowers/Marigold.jpg
    - assets/Product/Flowers/MarigoldWhite.jpg
    - assets/Product/Flowers/MawarPink.jpg
    - assets/Product/Flowers/Kedupul.jpg
    - assets/Product/Flowers/MawarJuliet.jpg
    - assets/Product/Flowers/AnggrekNS.jpg
    - assets/Product/Flowers/AnggrekMawar.jpg
    - assets/Product/Flowers/AnggrekBulan.jpg
    - assets/Product/Flowers/Melati.jpg
    - assets/Product/Flowers/AmorphophallusTitanum.jpg
    - assets/Product/Flowers/RafflesiaArnoldii.jpg
    - assets/Product/Flowers/AnthuriumMerah.jpg
    - assets/Product/Flowers/CamelliaPink.jpg
    - assets/Product/Flowers/MorningGlory.jpg
    - assets/Product/Flowers/MorningGloryRarePink.jpg
    - assets/Product/Flowers/Nasturtium.jpg
    - assets/Product/Flowers/PenutiaUngu.jpg
    - assets/Product/Flowers/PoppyMerah.jpg
    - assets/Product/Flowers/Zinnia.jpg
    - assets/Product/Flowers/Primrose.jpg
    - assets/Product/Flowers/Rhododendron.jpg
    - assets/Product/Flowers/SweetPea.jpg
    - assets/Product/Flowers/HydrangeaBiru.jpg
    - assets/Product/Flowers/GerberaDaisy.jpg
    - assets/Product/Flowers/PeonyPink.jpg
    - assets/Product/Flowers/CarnationRed.jpg
    - assets/Product/Flowers/Snapdragon.jpg
    - assets/Product/Flowers/BegoniaMerah.jpg
    - assets/Product/Flowers/AzaleaPink.jpg
    - assets/Product/Flowers/DahliaMerah.jpg
    - assets/Product/Flowers/Fuchsia.jpg
    - assets/Product/Flowers/MarigoldKuning.jpg
    - assets/Product/Flowers/AnggrekBulann.jpg
    - assets/Product/Flowers/TulipMerah.jpg
    - assets/Product/Flowers/KaktusMini.jpg
    - assets/Product/Flowers/LidahBuaya.jpg
    - assets/Product/Flowers/BungaMatahari.jpg
    - assets/Product/Flowers/Jasmine.jpg
    - assets/Product/Flowers/Bougainvillea.jpg
    - assets/Product/Flowers/LiliPutih.jpg
    - assets/Product/Flowers/KrisanKuning.jpg
    - assets/Product/Flowers/Lavenderr.jpg
    - assets/Product/Flowers/HibiscusMerah.jpg
    - assets/Product/Flowers/AmaryllisMerah.jpg
    - assets/Product/Flowers/CyclamenPink.jpg
    - assets/Product/Flowers/CallaLilyPutih.jpg
    - assets/Product/Flowers/ClematisUngu.jpg
    - assets/Product/Flowers/DelphiniumBiru.jpg
    - assets/Product/Flowers/DianthusMerah.jpg
    - assets/Product/Flowers/EchinaceaPurpurea.jpg
    - assets/Product/Flowers/FreesiaKuning.jpg
    - assets/Product/Flowers/GardeniaPutih.jpg
    - assets/Product/Flowers/HeleniumMerah.jpg
    - assets/Product/Flowers/IrisBiru.jpg
    - assets/Product/Flowers/JasmineSambac.jpg
    - assets/Product/Flowers/LantanaWarna-warni.jpg
    - assets/Product/Flowers/LotusPutih.jpg
    - assets/Product/Flowers/MagnoliaPink.jpg
    - assets/Product/Flowers/TulipMerahh.jpg
    - assets/Product/Flowers/AnggrekPutih.jpg
    - assets/Product/Flowers/LavenderUngu.jpg
    - assets/Product/Flowers/MawarKuning.jpg
    - assets/Product/Flowers/DahliaMerahh.jpg
    - assets/Product/Flowers/BegoniaPink.jpg
    - assets/Product/Flowers/HydrangeaBiruu.jpg
    - assets/Product/Flowers/LilyKuning.jpg
    - assets/Product/Flowers/PetuniaUngu.jpg
    - assets/Product/Flowers/SnapdragonMerah.jpg
    - assets/Product/Flowers/MarigoldKuningg.jpg
    - assets/Product/Flowers/PeonyPinkk.jpg
    - assets/Product/Flowers/ZinniaWarna-warni.jpg
    - assets/Product/Flowers/RanunculusMerah.jpg
    - assets/Product/Flowers/TulipMerahhh.jpg
    - assets/Product/Flowers/AnggrekPutihh.jpg
    - assets/Product/Flowers/LavenderUnguu.jpg
    - assets/Product/Flowers/MawarKuningg.jpg
    - assets/Product/Flowers/DahliaMerahhh.jpg
    - assets/Product/Flowers/MawarBiru.jpg
    - assets/Product/Flowers/BungaDahlia.jpg
    - assets/Product/Flowers/LiliPutihh.jpg
    - assets/Product/Flowers/BungaKamboja.jpg
    - assets/Product/Flowers/BungaKaktus.jpg
    - assets/Product/Flowers/BungaAnggrekBulan.jpg
    - assets/Product/Flowers/BungaHortensia.jpg
    - assets/Product/Flowers/BungaBegonia.jpg
    - assets/Product/Flowers/BungaGladiol.jpg

  #- assets/Product/Flowers/.jpg

#Alat
    - assets/Product/Alat/PotBunga.jpg
    - assets/Product/Alat/STB.jpg
    - assets/Product/Alat/VitaminTanaman.jpg
    - assets/Product/Alat/AST.jpg
    - assets/Product/Alat/PupukOrganik.jpg
    - assets/Product/Alat/PotTanaman.jpg
    - assets/Product/Alat/SekopMini.jpg
    - assets/Product/Alat/ObatAntiHama.jpg
    - assets/Product/Alat/GuntingTanaman.jpg
    - assets/Product/Alat/BenihBungaMatahari.webp
    - assets/Product/Alat/PenyiramTanaman.jpg
    - assets/Product/Alat/KomposCair.jpg
    - assets/Product/Alat/PeralatanBerkebun.jpg
    - assets/Product/Alat/BenihKaktus.jpg
    - assets/Product/Alat/PupukKandang.jpg
    - assets/Product/Alat/BajaKompos.jpg
    - assets/Product/Alat/KantongTanah.jpg
    - assets/Product/Alat/PupukCair.jpg
    - assets/Product/Alat/MulsaOrganik.jpg
    - assets/Product/Alat/PenyemprotOtomatis.jpg
    - assets/Product/Alat/BajaSerbuk.jpg
    - assets/Product/Alat/BenihBonsai.jpg
    - assets/Product/Alat/KeranjangTanam.jpg
    - assets/Product/Alat/AlatCangkul.jpg
    - assets/Product/Alat/PupukKandangCair.jpg
    - assets/Product/Alat/BenihLavender.jpg
    - assets/Product/Alat/SprayerElektrik.jpg
    - assets/Product/Alat/HumusTanah.jpg
    - assets/Product/Alat/BajaSlowRelease.jpg
    - assets/Product/Alat/BenihMarigold.jpg
    - assets/Product/Alat/GemborTaman.jpg
    - assets/Product/Alat/BenihBayam.jpg
    - assets/Product/Alat/ObatPengendaliGulma.jpg
    - assets/Product/Alat/PotBungaKecil.jpg
    - assets/Product/Alat/CangkirTanam.jpg
    - assets/Product/Alat/BenihMawar.jpg
    - assets/Product/Alat/VitaminTanamann.jpg
    - assets/Product/Alat/BenihTulip.jpg
    - assets/Product/Alat/AlatPenyiramTanaman.jpg
    - assets/Product/Alat/ObatAntiHamaa.jpg
    - assets/Product/Alat/PupukKomposCair.jpg
    - assets/Product/Alat/BenihAnggrek.jpg
    - assets/Product/Alat/PotGantung.jpg
    - assets/Product/Alat/BenihMelati.jpg
    - assets/Product/Alat/SekopTangan.jpg
    - assets/Product/Alat/MediaTanamOrganik.jpg
    - assets/Product/Alat/PupukDaun.jpg
    - assets/Product/Alat/BenihSunflower.jpg
    - assets/Product/Alat/PupukOrganikPadat.jpg
    - assets/Product/Alat/BenihPakis.jpg
    - assets/Product/Alat/AlatPemangkasTanaman.jpg
    - assets/Product/Alat/BenihZinnia.jpg
    - assets/Product/Alat/ObatAntiJamur.jpg
    - assets/Product/Alat/BenihPeony.jpg
    - assets/Product/Alat/BenihBungaMatahari.jpg
    - assets/Product/Alat/BenihMarigoldd.jpg
    - assets/Product/Alat/BenihLavenderr.jpg

  #  - assets/Product/Alat/.jpg





    #Payment
    - assets/Payment/Gopay.png
    - assets/Payment/LinkAja.png
    - assets/Payment/Ovo.png
    - assets/Payment/ShopeePay.png
    - assets/Payment/Dana.png
    - assets/Payment/BCA.png
    - assets/Payment/Mandiri.png
    - assets/Payment/BNI.png
    - assets/Payment/BRI.png
    - assets/Payment/BSI.png
    - assets/Payment/PermataBank.png
    - assets/Payment/SeaBank.png
    - assets/Payment/BankMega.png
    - assets/Payment/UOB.png
    - assets/Payment/Maybank.png
    - assets/Payment/DBS.png
    - assets/Payment/Jenius.png
    - assets/Payment/Danamon.png
    - assets/Payment/CimbNiaga.png
    - assets/Payment/AgenBRILink.png
    - assets/Payment/Alfamart.png
    - assets/Payment/Indomaret.png
    - assets/Payment/BNIagen46.png
